// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as customerr$0 from "./shared/customerr/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as response$0 from "./shared/response/models.js";

export function GetTrackInfo(): Promise<[response$0.TrackInfo[] | null, customerr$0.ErrorResponse | null]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(890784923) as any;
    return $resultPromise;
}
