// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ValidationError = "ValidationError",
    NotFoundError = "NotFound",
    InternalError = "InternalError",
};
