// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../enums/models.js";

export interface ErrorData {
    "field": string;
    "message": string;
}

export interface ErrorResponse {
    "code": enums$0.ErrorCode;
    "data": ErrorData | null;
}
